name: WhitelistBot
main: windowx.minecraft.plugin.WhitelistBot
version: 1.0
depend:
  - MiraiCore
commands:
  wb:
    usage: /wb <args>
    permission: whitelistbot.commands.wb
  l:
    usage: /l <密码>
    permission: whitelistbot.commands.l
  reg:
    uasge: /reg <密码> <再次输入密码>
    permission: whitelistbot.commands.reg
